[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Use the LLD linker (much faster than arm-none-eabi-ld)
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
# The specific target for the LPC55S69 (Cortex-M33 with FPU)
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
# Use probe-rs to flash and debug immediately with 'cargo run'
runner = "probe-rs run --chip LPC55S69"